---
# Configure services - runs after the install stage

- name: Create directory for libvirt socket
  file:
    state: directory
    path: "{{ libvirt_host_socket_dir }}"
    owner: root
    group: root
    mode: 0755
  become: true
  when: libvirt_host_socket_dir | length > 0

- name: Process lineinfile rules
  lineinfile: "{{ rule.args }}"
  become: true
  loop: "{{ libvirt_host_lineinfile_extra_rules | default([]) }}"
  loop_control:
    loop_var: rule
  when: rule.condition
  notify:
    - restart libvirt

- name: Ensure configuration files exist
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  become: true
  loop: "{{ _libvirt_config_files | selectattr('enabled') }}"
  loop_control:
    label: "{{ item.dest | basename }}"
  vars:
    _libvirt_config_files:
      - src: libvirtd.conf.j2
        dest: /etc/libvirt/libvirtd.conf
        enabled: "{{ libvirt_host_libvirtd_conf_enabled | bool }}"
      - src: qemu.conf.j2
        dest: /etc/libvirt/qemu.conf
        enabled: "{{ libvirt_host_qemu_conf_enabled | bool }}"
  notify:
    - restart libvirt

- name: Flush handlers
  meta: flush_handlers

- name: Ensure the libvirt daemon is started and enabled
  service:
    name: libvirtd
    state: started
    enabled: yes
  become: True
